spring:
    datasource:
        generate-unique-name: false
        name: notecloud
        url: jdbc:h2:file:~/noteclouddb
        username: sa
        password: password
        driver-class-name: org.h2.Driver
    session:    
        jdbc:
            initialize-schema: always
    sql:
        init:
            mode: always
