create table if not exists USERS (
	id bigint generated by default as identity primary key,
	username varchar_ignorecase(50) unique,
	password varchar_ignorecase(500)
);

create table if not exists NOTES (
    id bigint generated by default as identity primary key,
	user_id bigint,
	foreign key (user_id) references USERS(id),
    title varchar(32) not null,
	content varchar(256) not null
);
